### ISSUE TITLE
how to implement a reconcile function

### ISSUE THREAD

**Issue by f-minzoni** [clux/controller-rs#2]
Hi, thanks to having provided this inspiring project. If I'm not wrong, the operator acts like a k8s controller, creating the resource reflector and managing the control loop in the state::init for keeping in sync the store. I'm wondering where/how I can define a reconcile function in the operator itself to trigger other behaviors accordingly to event notifications. I mean, if I want to create new k8s objects after a new Foo resource has been added, what is your suggestion to implement this? Thanks

**Comment by clux** [comment]
Yeah, that's a good question atm.

We totally need some mechanism to  bubble the events upwards, but that abstraction has not been written in [kube-rs](https://github.com/clux/kube-rs) yet. Maybe this is an `Informer`, or maybe we can just expose the events directly.

If you don't need to only act on just the changed ones, it's possible to use api calls on stuff in the state via `k8s-openapi`, which can be passed our api client. But it would be better not to have to reconcile the entire state set every loop :D

**Comment by clux** [comment]
Tracking issue in https://github.com/clux/kube-rs/issues/5

**Comment by f-minzoni** [comment]
Right, it's definitely useful an Informer where add custom event handlers. Following the pattern of Kubebuilder (https://github.com/kubernetes-sigs/kubebuilder) at some point, almost all the reusable logic could be wrapped in a Manager. The Controller watches for resource events, and calls Reconcile with the resource key.

**Comment by clux** [comment]
I'll have a look at it. Ultimately, I'm not sure how much of the normal go kube controller conventions will be followed here. Api niceness in rust is preferred.

Anyway, a first sketch is availble now in https://github.com/clux/kube-rs/blob/master/examples/pod_reconcile.rs - will probably release it as 0.4.0 later.

Might be refactored into something else, but it's at least useable!

**Comment by f-minzoni** [comment]
It looks great!

**Comment by clux** [comment]
Thanks! The kubebuilder docs were very useful.

Have had a stab at creating Informers in https://github.com/clux/kube-rs#informers for 0.5.0
If you do try it out, please report any bugs :sweat_smile: 

Closing this for now.
