### ISSUE TITLE
can you give me an example to create a statefulSet when reconcile the CR

### ISSUE THREAD

**Issue by carolove** [clux/controller-rs#5]
hi, i found it is difficult for me to use k8s_openapi, i want to create a statefulSet, and apply into k8s, when reconcile the CR, i can't find the right way, can you help me, i'm an newer in rust.

**Comment by clux** [comment]
You probably need an `Informer<v1StatefulSet>` and a `sets = Api<v1StatefulSet>. Then use sets.replace(myset)` when you get a modified event in the informer. Try a rust help channel somewhere, this is not an issue here.
